# Generated by Django 3.0.7 on 2020-06-13 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=7)),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('outcome', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('role', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('is_ibl_unit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Placement')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=256)),
                ('family_name', models.CharField(max_length=256)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=256)),
                ('family_name', models.CharField(max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interview')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supervisor')),
            ],
        ),
        migrations.AddField(
            model_name='placement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
        migrations.AddField(
            model_name='company',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interview'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=256)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interview')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
        ),
    ]
