# Generated by Django 3.0.7 on 2020-06-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200613_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Placement'),
        ),
    ]
