# Generated by Django 3.0.7 on 2020-06-13 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200613_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('is_ibl_unit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Placement')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=256)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
        ),
    ]
