image: python:3.8

variables:
  AWS_DEFAULT_REGION: "ap-southeast-2"
  # variables set in gitlab's web gui:
  #   AWS_ACCESS_KEY_ID
  #   AWS_SECRET_ACCESS_KEY
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.pip-cache

cache:
  paths:
    - $CI_PROJECT_DIR/.pip-cache

stages:
  - build
  - test
  - deploy

".deploy-base":
  stage: deploy
  before_script:
    # Write env variables to the .env file
    - echo "Gitlab CI environment = "$CI_ENVIRONMENT_NAME
    - echo "DATABASE_URL = "$DATABASE_URL >> .env
    # Create virtual environment and install packages
    - python -V
    - python -m venv env
    - source env/bin/activate
    - pip install -r requirements.txt
    # Make Django migrations before deploying package to Lambda
    - python manage.py makemigrations
  script:
    # creating aws credentials file
    - mkdir -p ~/.aws
    - echo "[default]" >> ~/.aws/credentials
    - echo "aws_access_key_id = "$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
    - echo "aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
    # try to update, if the command fails (probably not even deployed) do the initial deploy
    - zappa update $ZAPPA_STAGE || zappa deploy $ZAPPA_STAGE
    - zappa manage $ZAPPA_STAGE create_admin_user || echo "Admin user already exists"
    - zappa manage $ZAPPA_STAGE migrate
  after_script:
    # - cat ~/.aws/credentials
    - rm ~/.aws/credentials

deploy-dev:
  extends: .deploy-base
  environment:
    name: dev
  variables:
    ZAPPA_STAGE: dev
  only:
    - dev

deploy-prod:
  extends: .deploy-base
  environment:
    name: prod
  variables:
    ZAPPA_STAGE: prod
  only:
    - master
