# Generated by Django 3.0.7 on 2020-09-11 13:08

import core.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_started',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='semester_preference',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('C', 'Completed')], default=('I', 'Incomplete'), max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_preference',
            field=models.PositiveIntegerField(validators=[core.api.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[core.api.validators.validate_course_code]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='outcome_details',
            field=models.CharField(blank=True, choices=[('S', 'Successful'), ('U', 'Unsuccessful')], max_length=1),
        ),
        migrations.AlterField(
            model_name='placement',
            name='year',
            field=models.PositiveIntegerField(validators=[core.api.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='student',
            name='WAM',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[core.api.validators.validate_student_wam]),
        ),
        migrations.AlterField(
            model_name='student',
            name='credit_points',
            field=models.PositiveIntegerField(validators=[core.api.validators.validate_credit_points]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=256, validators=[core.api.validators.validate_school_email]),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[core.api.validators.validate_student_id]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, validators=[core.api.validators.validate_unit_code]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='year',
            field=models.PositiveIntegerField(validators=[core.api.validators.validate_year]),
        ),
    ]
