# Generated by Django 3.0.7 on 2020-09-13 09:46

import core.api.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200911_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(validators=[core.api.validators.validate_year])),
                ('semester', models.PositiveIntegerField()),
                ('Pass', models.BooleanField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
        ),
    ]
