# Generated by Django 3.0.7 on 2020-09-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200623_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, upload_to='application/cv/'),
        ),
    ]
