# Generated by Django 3.0.7 on 2020-09-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentunit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentUnit',
            new_name='StudentandUnit',
        ),
        migrations.RenameField(
            model_name='studentandunit',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentandunit',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
