# Generated by Django 3.0.7 on 2020-09-14 03:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200913_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMapSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Snapshot', models.TextField()),
                ('approval', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Application')),
            ],
        ),
    ]
