# Generated by Django 3.0.7 on 2020-10-20 04:58

import core.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coursemapsnapshot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentandUnit',
            new_name='StudentUnit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='semester',
            new_name='credit_points',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='year',
        ),
        migrations.AddField(
            model_name='unit',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitcourse',
            name='semester',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitcourse',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[core.api.validators.validate_year]),
            preserve_default=False,
        ),
    ]
