# Generated by Django 3.0.9 on 2020-10-30 10:11

import core.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201020_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitcourse',
            name='year',
            field=models.PositiveIntegerField(validators=[core.api.validators.validate_unitcourse_year]),
        ),
    ]
