# Generated by Django 3.0.7 on 2020-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200825_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
