# Generated by Django 3.0.7 on 2020-08-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200825_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='unit',
        ),
    ]
