# Generated by Django 3.0.9 on 2020-10-30 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201030_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=models.CASCADE, null=True, to='core.Student')),
                ('supervisor', models.ForeignKey(on_delete=models.CASCADE, to='core.Supervisor')),
                ('title', models.TextField()),
                ('notes', models.TextField(blank=True)),

                ('application', models.ForeignKey(on_delete=models.CASCADE, null=True, to='core.Application')),
                ('location', models.CharField(max_length=256, blank=True)),
                ('outcome_details',
                 models.CharField(max_length=1, blank=True, choices=[("S", "Successful"), ("U", "Unsuccessful")])),
                ('company', models.ForeignKey(on_delete=models.CASCADE, null=True, to='core.Company')),
            ],
        ),
    ]
