# Generated by Django 3.0.7 on 2020-11-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201030_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student_response',
            field=models.ForeignKey(default='42b4c31a-7163-4c36-9ab6-2c61d6d50a7e', on_delete=django.db.models.deletion.CASCADE, to='core.StudentResponse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('C', 'Completed')], max_length=1),
        ),
    ]
