# Generated by Django 3.0.9 on 2020-10-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201030_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InterviewSlot'),
        ),
    ]
