# Generated by Django 3.0.7 on 2020-08-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_application_unit'),
        ('core', '0003_questionnairetemplate'),
    ]

    operations = [
    ]
