# Generated by Django 3.0.9 on 2020-10-30 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_interview_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='time',
        ),
        migrations.DeleteModel(
            name='InterviewSlot'
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=models.CASCADE, blank=True, to='core.Application'),
        ),
        migrations.AddField(
            model_name='interview',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='interview',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='interview',
            name='title',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='interview',
            name='staff',
        ),
        migrations.AddField(
            model_name='interview',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supervisor'),
        ),
    ]
